name: Build Release


on:
  push:
    tags:
      - '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -yq libboost-dev

    - name: Build
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        
        cd ${{github.workspace}}/ggml
        cmake -B ${{github.workspace}}/ggml/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_EXE_LINKER_FLAGS="-static"
        cd ${{github.workspace}}/ggml/build 
        make codegen codegen-serve codegen-quantize
        chmod +x ${{github.workspace}}/ggml/build/bin/codegen 
        chmod +x ${{github.workspace}}/ggml/build/bin/codegen-serve 
        chmod +x ${{github.workspace}}/ggml/build/bin/codegen-quantize
        
        

    - name: Prepare Release
      run: |
        cd /${{github.workspace}}/ggml/build/bin/
        zip ${{github.workspace}}/ggml/build/bin/release.zip \
          codegen codegen-serve codegen-quantize


    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/ggml/build/bin/release.zip
        asset_name: turbopilot-${{ runner.os }}-${{ runner.arch }}-${{ steps.short-sha.outputs.sha }}-{{ github.ref }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Turbopilot binary release"