name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Login to GH ContainerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ravenscroftj
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/ravenscroftj/turbopilot
        context: ${{github.workspace}}
      
    # - name: Publish Docker Image to GitHub Registry
    #   # You may pin to the exact commit or the version.
    #   # uses: TilBlechschmidt/gp-docker-action@f89287d44556dd7d24f76c799cd0795eeb352bcf
    #   uses: TilBlechschmidt/gp-docker-action@v0.2-alpha
    #   with:
    #     # GitHub token to push Docker image to GitHub Packages
    #     github-token: ${{ secrets.GH_TOKEN }}
    #     # Docker Image name
    #     image-name: turbopilot
    #     # Path to the directory where the Dockerfile resides
    #     dockerfile-path: . # optional, default is .
